mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("tyuusenn/", include("tyuusenn.urls")),
    path("admin/", admin.site.urls),
]

tyuusenn/urls.py
from django.urls import path
from django.conf.urls.static import static
from . import views
from django.conf import settings
app_name = 'tyuusenn'
urlpatterns = [
    path('', views.Login, name='Login'),
    path("logout",views.Logout,name="Logout"),
    path('home', views.index, name='index'),
    path('i_ajax/',views.i_ajax,name='i_ajax'),
    #path('y',views.Yosouhe.as_view(),name="yosouhe"),
    path('yosou',views.yosouhee,name="yosouhe1"),
    path('sousuhe',views.sousuhe,name="sousuhe"),
    path('gurahu',views.Index2.as_view(),name='Index2'),
    ]+ static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

tyuusenn/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Device(models.Model):
    name = models.CharField(max_length=255)
    touhyou = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10000)])
    bikou = models.CharField(max_length=255)

    def __str__(self):
        return self.name

tyuusenn/views.py
from django.http import HttpResponse
from django.shortcuts import render
import random
from datetime import datetime, date
from apscheduler.schedulers.background import BackgroundScheduler
import sys
from django.views.generic import View, DetailView, TemplateView
from datetime import datetime, date
from . import g
from .models import Device
from django.urls import reverse_lazy
import japanize_matplotlib
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse


class X1:  # グローバルな変数を用意するためだけの存在
    kazu = {"a": 0}


x2 = X1()


def start():
    scheduler = BackgroundScheduler()
    scheduler.add_job(rannsuu, "interval", seconds=5)  # 5秒おきに実行
    scheduler.start()


def rannsuu():  # 任意の関数名  # ここに定期実行したい処理を記述する
    # print("ただいまテスト中")
    x3 = random.randint(1, 18)  # ランダムにid生成。上のクラスのを上書きもする。
    x2.kazu = {"x": x3}
    i = x2.kazu["x"]  # 部屋のidをランダムで取得
    i2 = Device.objects.get(pk=i)
    print(i2)  # テスト出力
    i2.touhyou = i2.touhyou + 1  # 投票数１プラス
    print(i2.touhyou)  # テスト出力
    i2.save()


# 本番環境で二回行動するようなら奇数の時選ばれたのを-1マイナス処理で対応


@login_required
def index(request):
    # print(x2.kazu)
    contacts = Device.objects.all
    context = {
        "test": contacts,
    }

    return render(request, "home.html", context)


# 　ajax用view
class c_AjaxView(View):
    def get(self, request):
        i = x2.kazu["x"]  # 部屋のidをランダムで取得
        i2 = Device.objects.get(pk=i)
        context = {"test1": i2.name}
        return HttpResponse(context.values(), request)


i_ajax = c_AjaxView.as_view()


# 本番環境で二回行動するようなら奇数の時選ばれたのを-1マイナス処理で対応(重要)


@login_required
def yosouhee(request):  # homeから予想のボタンの押されたら遷移させる
    if request.method == "POST":
        return render(request, "home2.html")


@login_required
def sousuhe(request):  # homeからソースコードのボタンの押されたら遷移させる
    if request.method == "POST":
        return render(request, "home3.html")


"""
def kaeru(request): #yosouから投票場ボタンの押されたら遷移させる
    if request.method == 'POST':
        contacts = Device.objects.all
        context = {
            'test': contacts,
        }
    
        return render(request, 'home.html',context)

"""


class Index2(TemplateView):

    # テンプレートファイル連携
    template_name = "home2.html"

    # 変数としてグラフイメージをテンプレートに渡す
    def get_context_data(self, **kwargs):

        # グラフオブジェクト
        qs = Device.objects.all()  # モデルクラス(ProductAテーブル)読込
        x = [x.name for x in qs]  # X軸データ
        y = [y.touhyou for y in qs]  # Y軸データ
        # color = [('b' if i == max(x) else 'r') for i in x] # 最大の奴だけ色変える

        chart = g.Plot_Graph(x, y)  # グラフ作成

        # 変数を渡す
        context = super().get_context_data(**kwargs)
        context["chart"] = chart
        return context

    # get処理
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


# ログイン
def Login(request):
    # POST
    if request.method == "POST":
        # フォーム入力のユーザーID・パスワード取得
        ID = request.POST.get("userid")
        Pass = request.POST.get("password")

        # Djangoの認証機能
        user = authenticate(username=ID, password=Pass)

        # ユーザー認証
        if user:
            # ユーザーアクティベート判定
            if user.is_active:
                # ログイン
                login(request, user)
                # ホームページ遷移
                return HttpResponseRedirect(reverse("tyuusenn:index"))
                """
                contacts = Device.objects.all
                context = {
                'test': contacts,
                    }
                    
    
                return render(request, 'home.html',context)
                """
            else:
                # アカウント利用不可
                return HttpResponse("アカウントが有効ではありません")
        # ユーザー認証失敗
        else:
            return HttpResponse("ログインIDまたはパスワードが間違っています")
    # GET
    else:
        return render(request, "login.html")


# ログアウト
@login_required
def Logout(request):
    if request.method == "POST":
        logout(request)
        # ログイン画面遷移
        return HttpResponseRedirect(reverse("tyuusenn:Login"))

templates/base.html
<!DOCTYPE html>
<html lang="ja">
<html>

<head>

</head>

<body>
  {% block content %}{% endblock %}
  <nav class="navbar navbar-dark bg-primary">
    <div class="container-fluid">
      <div>
        <a class="navbar-brand" href="#">
          <i class="bi bi-bootstrap-fill" style="font-size: 2rem;"></i>
        </a>
      </div>
      <div class="flex-grow-1" style="max-width:500px;">
        <form class="d-flex" method="GET">
          <input class="form-control me-2" type="search" placeholder="検索..." aria-label="Search" name="search">
          <button class="btn btn-outline-light" type="submit">search</button>
        </form>
      </div>
      <div class="text-light nav-item dropdown">
        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button"
          data-bs-toggle="dropdown" aria-expanded="false">
          ユーザー名
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="#">アカウント設定</a></li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item" href="#">ログアウト</a></li>
        </ul>
      </div>
    </div>
  </nav>

</body>

</html>

templates/home.html
<!DOCTYPE html>
<html lang="ja">

<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="refresh" content="30; URL="> <!--30秒で自動更新 -->
    <title>template test</title>
    {% load static %}
    <!--<link rel="stylesheet" href="{% static 'ccc.css' %}"> -->
    <!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="{% static 'matome.css' %}"> <!--importしてる-->
</head>

<body>



    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- navbar-inverse で黒系ナビゲーションの指定をしています。-->
        <!-- navbar-fixed-top でヘッダー固定の指定をしています。-->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span
                        class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                <!--button~はウインドウのサイズが780px以下になった時に表示されます。-->
                <a class="navbar-brand" href="#">抽選場</a>
                <!--こちらにサイト名を入れます。-->
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <!--<li class="active"><a href="#home">ホーム</a></li>-->
                    <li>
                        <form action="{% url 'tyuusenn:yosouhe1' %}" method="POST">
                            {% csrf_token %}


                            <input type="submit" value="グラフで見る"></a>
                        </form>
                    </li>
                    <li>
                        <form action="{% url 'tyuusenn:sousuhe' %}" method="POST">
                            {% csrf_token %}


                            <input type="submit" value="サイトの抽選プログラムのソースコードを見に行く"></a>
                        </form>
                    </li>
                    <li>
                        <form action="{% url 'tyuusenn:Logout' %}" method="POST">
                            {% csrf_token %}


                            <input type="submit" value="ログアウト"></a>
                        </form>
                    </li>>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>



    <!--<body background="{% static 'tt.png' %}" > --背景画像をここで読み込む予定でしたがCSSで読み込むことに -->






    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script>
        function get_time() {
            // Ajax通信処理
            $.ajax({
                // リクエスト送信先URLの設定
                url: '{% url "tyuusenn:i_ajax" %}',　　// ここで、i_ajaxViewを呼び出している。
                // 非同期通信フラグ（trueは非同期）
                async: true,
                // Ajax通信成功時にレスポンスデータ受け取り&処理実行
                success: function (data) {
                    document.getElementById("auto").innerHTML = data;
                }
            });
        }
        // 5秒ごとに実行する
        $(document).ready(function () {
            setInterval(get_time, 5000);
        });
    </script>
    <br>
    <br>
    <br>
    <br>
    <br>
    <b>
        <p>水道料金当番投票場へようこそ 30秒に一回投票数が更新されます。</p>
    </b>
    <b>
        <p>あなたの部屋番号は　303号室 です</p>
    </b>
    <b>
        <p>異動等により当番を受け持つことができない場合や、当番を引き受けてくださる方がいらっしゃいましたらお手数ですが３０３号室の小倉までご連絡ください。</p>
    </b>
    <div
        style=" color: white; background: #f98289; height:100px; padding: 20px; border: 2px dashed rgba(255 , 255 , 255 , 0.5);-moz-border-radius: 6px; -moz-box-shadow: 0 0 0 5px #f98289 , 0 2px 3px 5px rgba(0 , 0 , 0 , 0.5); -webkit-border-radius: 6px; -webkit-box-shadow: 0 0 0 5px #f98289 , 0 2px 3px 5px rgba(0 , 0 , 0 , 0.5); border-radius: 6px; box-shadow: 0 0 0 5px #f98289 , 0 2px 3px 5px rgba(0 , 0 , 0 , 0.5); font-size: 150%; ">

        <u><b>
                <h2 id="auto" style="text-align:center;"></h2>
            </b></u><!--ここに投票先の部屋番号表示-->

    </div>
    <br>
    <b>
        <p style="text-align:center;">の部屋番号の方に一票</p>
    </b>



    {% for names in test %}
    <table border="2" width="300" height="50">
        <tr>
            <td><b>{{ names.name }}</b></td>
            <td><b>投票数:{{ names.touhyou }}</b></td>
            <td><b>{{ names.bikou }}</b></td>
            <td><b>id:{{ names.id }}</b></td>
        </tr>
    </table>
    {% endfor %}


    </script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>




</body>

</html>

templates/home2.html
<!DOCTYPE html>
<html lang="ja">
<html>

<head>
    <title>template test</title>
    {% load static %}

    <style>
        .txt {
            width: 20em;
            height: 5em;
        }
    </style>
</head>

<body>

    <body background="{% static 'vs.png' %}">

        <div
            style="padding: 20px; background: #fff; -webkit-box-shadow: 0 0 50px #f98289 inset, 5px 5px 0 #cecece; -moz-box-shadow: 0 0 50px #f98289 inset, 5px 5px 0 #cecece; box-shadow: 0 0 50px #f98289 inset, 5px 5px 0 #cecece; font-size: 100%;">
            <h3><b>グラフを出力・更新する　のボタンを押すと押した時点での投票数をグラフ形式でご覧になれます。</b></h3>
        </div>
        <img src="data:image/png;base64,{{ chart | safe }}">
        <form action="{% url 'tyuusenn:index' %}" method="get">
            {% csrf_token %}

            <input type="submit" class="txt" value="投票場に帰る">
        </form>

        <form action="{% url 'tyuusenn:Index2' %}" method="get">
            {% csrf_token %}

            <input type="submit" class="txt" value="グラフを出力・更新する">
        </form>

    </body>

</html>

templates/home3.html
<!DOCTYPE html>
<html lang="ja">
<html>

<head>

</head>

<body>
    <br>pythonのdjangoで作成した抽選部分のプログラムになります。</br>
    <br>このページに貼り付けた時点のソースコード、実験環境で動かした際のソースコードですので</br>
    <br>実際の動作環境に移した際の調整により 多少の内容の変更がある可能性がありますが、</br>
    <br>①BackgroundSchedulerで定期的にプログラム実行 </br>
    <br>②random.randintで抽選 </br>
    <br>③Deviceモデルに投票数を追加し、</br>
    <br>BackgroundSchedulerの実行間隔と同間隔でajax通信にてhtmlに出力(ホームページに出力)</br>
    <br>という流れは同様です。</br>

    <code>
        <ol style="list-style:decimal-leading-zero outside;in-left:0;padding-left:36px;margin:0;background-color:#EEF;color:#000;">
        <li style="background-color:#EFF;">from django.http import HttpResponse</li>
        <li style="background-color:#EEF;">from django.shortcuts import render</li>
        <li style="background-color:#EFF;">import random</li>
        <li style="background-color:#EEF;">from datetime import datetime, date</li>
        <li style="background-color:#EFF;">from apscheduler.schedulers.background import BackgroundScheduler</li>
        <li style="background-color:#EEF;">import sys </li>
        <li style="background-color:#EFF;">from django.views.generic import View,DetailView,TemplateView</li>
        <li style="background-color:#EEF;">from datetime import datetime, date</li>
        <li style="background-color:#EFF;">from .import test</li>
        <li style="background-color:#EEF;">from .models import Device</li>
        <li style="background-color:#EFF;">from django.urls import reverse_lazy</li>
        <li style="background-color:#EEF;">import japanize_matplotlib</li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;">class X1: #グローバルな変数を用意するためだけの存在</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;kazu = {<font style="color:brown;">"a"</font>:0}</li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;">x2 = X1()</li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;">def start():</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;scheduler = BackgroundScheduler()</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;scheduler.add_job(rannsuu, <font style="color:brown;">'interval'</font>,  seconds=5)#5秒おきに実行</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;scheduler.start()</li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;">def rannsuu(): # 任意の関数名  # ここに定期実行したい処理を記述する</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;#print(<font style="color:brown;">"ただいまテスト中"</font>)</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;x3 = random.randint(1,18) #ランダムにid生成。上のクラスのを上書きもする。</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;x2.kazu = {</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;<font style="color:brown;">'x'</font>: x3</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;}</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;i = x2.kazu[<font style="color:brown;">"x"</font>] #部屋のidをランダムで取得</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;i2 = Device.objects.get(pk=i)</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;print(i2) #テスト出力</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;i2.touhyou = i2.touhyou + 1 #投票数１プラス</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;print(i2.touhyou) #テスト出力</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;i2.save() </li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;">#本番環境で二回行動するようなら奇数の時選ばれたのを-1マイナス処理で対応</li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;">def index(request):</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;#print(x2.kazu)</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;contacts = Device.objects.all</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;context = {</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font style="color:brown;">'test'</font>: contacts,</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;}</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;return render(request, <font style="color:brown;">'home.html'</font>,context)</li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;">#　ajax用view</li>
        <li style="background-color:#EFF;">class c_AjaxView(View):</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;def get(self, request):</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i = x2.kazu[<font style="color:brown;">"x"</font>] #部屋のidをランダムで取得</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i2 = Device.objects.get(pk=i)</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context = {</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font style="color:brown;">'test1'</font>: i2.name</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;}</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return HttpResponse(context.values(),request)</li>
        <li style="background-color:#EFF;">i_ajax = c_AjaxView.as_view()</li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;">#本番環境で二回行動するようなら奇数の時選ばれたのを-1マイナス処理で対応(重要)</li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;">def yosouhee(request): #homeから予想のボタンの押されたら遷移させる</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;if request.method == <font style="color:brown;">'POST'</font>:</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return render(request, <font style="color:brown;">'home2.html'</font>)</li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;">def sousuhe(request): #homeからソースコードのボタンの押されたら遷移させる</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;if request.method == <font style="color:brown;">'POST'</font>:</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return render(request, <font style="color:brown;">'home3.html'</font>)</li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;"><font style="color:brown;">""</font><font style="color:brown;">"</li>
        <li style="background-color:#EEF;">def kaeru(request): #yosouから投票場ボタンの押されたら遷移させる</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;if request.method == 'POST':</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;contacts = Device.objects.all</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context = {</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'test': contacts,</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return render(request, 'home.html',context)</li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;">"</font><font style="color:brown;">""</font></li>
        <li style="background-color:#EEF;">class Index2(TemplateView):</li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;#テンプレートファイル連携</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;template_name = <font style="color:brown;">"home2.html"</font></li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;#変数としてグラフイメージをテンプレートに渡す</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;def get_context_data(self, **kwargs):</li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#グラフオブジェクト</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qs    = Device.objects.all()  #モデルクラス(ProductAテーブル)読込</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x     = [x.name for x in qs]           #X軸データ</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y     = [y.touhyou for y in qs]        #Y軸データ</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#color = [(<font style="color:brown;">'b'</font> if i == max(x) else <font style="color:brown;">'r'</font>) for i in x] # 最大の奴だけ色変える</li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chart = test.Plot_Graph(x,y)          #グラフ作成</li>
        <li style="background-color:#EFF;"></li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#変数を渡す</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context = super().get_context_data(**kwargs)</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context[<font style="color:brown;">'chart'</font>] = chart</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return context</li>
        <li style="background-color:#EEF;"></li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;#get処理</li>
        <li style="background-color:#EEF;">&nbsp;&nbsp;&nbsp;&nbsp;def get(self, request, *args, **kwargs):</li>
        <li style="background-color:#EFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return super().get(request, *args, **kwargs)</li>
        </ol></code>
    <form action="{% url 'tyuusenn:index' %}" method="get">
        {% csrf_token %}

        <input type="submit" class="txt" value="投票場に帰る">
    </form>
</body>

</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ja" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>


</head>

<body>
  <h1>ログイン画面</h1>

  <div class="reg">
    <form method="post" action="{% url 'tyuusenn:Login' %}">
      {% csrf_token %}

      <table class="reg_form">
        <tr>
          <td><label for="userid">ユーザーID:</label></td>
          <td><input type="text" name="userid"></td>
          <td><label for="password">パスワード：</label></td>
          <td><input type="password" name="password"></td>
        </tr>
      </table>

      <input type="submit" class="btn" value="Login">
    </form>
  </div>

</body>

</html>